### ISSUE TITLE
'hidapi-libusb' is required but it could not be found

### ISSUE THREAD

**Issue by babolivier** [phaazon/hid#2]
Hi,

As said in the title, hid require the hidapi-libusb package, which can't be found. I read that the file has been renamed, or something, but I don't have all the informations (I'm not really familiar with Haskell).
The consequence is that the package can't be installed anymore.

**Comment by phaazon** [comment]
Hi,

Thank you for your report. Do you have an idea what is the new name? Do you have a CHANGELOG somewhere about that?

**Comment by phaazon** [comment]
Ok, I should have read more carefully.

Actually, `hid` **doesn’t require any other package** else other than `base`, `bytestrings` and `transformers`. What you’re refering to is a **C library**. You have to install the C library before attempting to install the Haskell package. :)

**Comment by babolivier** [comment]
If you're talking about the `language-c` package, I've already installed it. Or are you talking about something else?

**Comment by phaazon** [comment]
The C library. [This](https://github.com/signal11/hidapi/tree/master/libusb).

**Comment by babolivier** [comment]
It works fine, thanks! And sorry for mistaking the library with a package :)

**Comment by phaazon** [comment]
No problem, that happens! I should update the documentation, it’s not even rightly written. Good luck with your HID needs. ;)
